### ISSUE TITLE
[Question] Where is test cases?

### ISSUE THREAD

**Issue by Modelizer** [amranidev/lpackager#1]
Hey,
  I found your package useful, you also integrated php-spec in composer but where is test cases? It help in many ways.. :)

**Comment by amranidev** [comment]
Whoops!!

:smile:  just added in composer cuz I'm planning to write test cases.

Any pull request about (php-spec or PHPUnit) test cases are welcome , I will be very thankful.

Cheers

**Comment by Modelizer** [comment]
I suggest you to release a stable branch with version tagging, integrate travis, integrate [Sensio lab code quality](https://insight.sensiolabs.com) or use [Style CI](http://styleci.io) . This will help user to be more secure.

And inshaAllah if i'l get time, i'l sure contribute to your repo. 👍 

Thanks.

**Comment by amranidev** [comment]
Thank you.

**Comment by amranidev** [comment]
@Modelizer, just added some tests,

Hopefully enjoying using it.

Cheers

**Comment by Modelizer** [comment]
👍  yes :)
