### ISSUE TITLE
Migration Commands

### ISSUE THREAD

**Issue by sarfraznawaz2005** [amranidev/lpackager#11]
Hi thanks for the package!

I can see that when we create a module, `Modules/ModuleName/database/migrations` folder is created. However `php artisan migrate` does not run any migrations from module folder. How do you run migrations from module's migration folder ?

Do you plan to add CLI commands for that ?

Thanks

**Comment by amranidev** [comment]
@sarfraznawaz2005 

Thank you for using Lpackager!!
Laravel already has migration command that you can specify your migration path, It would be duplicated if we re-create it.
So you may use the  --path option when executing the `php artisan migrate` command. The given path should be relative to your application's base path.

Check [Migrations](https://laravel.com/docs/5.3/migrations#generating-migrations)

**Comment by sarfraznawaz2005** [comment]
oh yes forgot it thanks :)
