### ISSUE TITLE
[Improvement] Require package should be pointed to dev.

### ISSUE THREAD

**Issue by Modelizer** [amranidev/lpackager#9]
I think this package is overall related to development. So, it must be pointed to `--dev`
Example right now in readme it's written `composer require Amranidev/Lpackager:dev-master` which should be `composer require Amranidev/Lpackager --dev` to get the lastest stable version and put it into `require-dev` block in `composer.json`.

Thanks

**Comment by amranidev** [comment]
@Modelizer 
Probably  right
may be a PR
Thanks for submitting this request :smile:
cheers!!
